TCONTROL-2506: Add aurora cpu credits alarm
nsbno/terraform-aws-alarms pull request #4
Opened 2024-05-21 14:59 UTC by SondreODahl

Jira: [TC-2506](https://vygruppen.atlassian.net/browse/TCONTROL-2506)

Første forsøk på å lage en alarm for når man går tom for CPU Credits i Aurora.

2024-05-22 06:46 UTC, asmundh commented on modules/aurora/main.tf
> +  metric_name = "CPUCreditBalance"
Mulig vi er mer interesserte i å trigge en alarm hvis vi må betale for ekstra credits (CPUSurplusCreditsCharged). 
På bildet av `CPUSurplusCreditBalance` leser vi at vi kan nedbetale det vi overskyter i samme døgn uten å betale ekstra. 
![image](https://github.com/nsbno/terraform-aws-alarms/assets/33457035/7edc93e0-33ae-4a3d-85b8-276672d3978f)


![image](https://github.com/nsbno/terraform-aws-alarms/assets/33457035/6a60ffd3-d035-4723-b8d0-a6ea9c1a9f68)

2024-05-22 11:17 UTC, asmundh commented on modules/aurora/main.tf
> +  evaluation_periods  = 3
Hvis vi anser det som alarm at det koster ekstra i det hele tatt så kan vi ha 1 periode

2024-05-22 11:18 UTC, asmundh approved these changes
LGTM 👍🏻 Utvikler Plattform bør også godkjenne

2024-05-22 11:27 UTC, SondreODahl commented on modules/aurora/main.tf
> +  evaluation_periods  = 3
Fikset

2024-05-22 11:43 UTC, nicolaei requested changes
Bare et lite nitpick, ellers topp!

Takk for bidraget 🔥

2024-05-22 11:43 UTC, nicolaei commented on modules/aurora/variables.tf
Fint om dere legger til disse variablene for å gjøre det likt de andre modulene:

```terraform
/*
 * == Alarm Configuration
 */

# Dette er `threshold`
variable "minimum_availiable_credits" {
  description = "Amount of credits left before alarm is triggered"
  type        = number
  default     = 0
}

variable "times_failed" {
  description = "Amount of elapsed evaluation periods before an alarm is triggered"
  type        = number
  default     = 1
}

variable "treat_missing_data" {
  description = "How this alarm is to handle missing data points"
  type        = string
  default     = "missing"
}

variable "period" {
  description = "Period in seconds to check for the applied statistic"
  type        = number
  default     = 60
}
```

De blir brukt sånn her: https://github.com/nsbno/terraform-aws-alarms/blob/master/modules/lambda/main.tf#L21-L24

2024-05-23 08:49 UTC, nicolaei requested changes
Bare noen nitpicks + fint om modulen blir renamet til `rds_overspent_instance_credits` eller lignende for å spesifisere alarmen litt mer 😄

2024-05-23 08:49 UTC, nicolaei commented on modules/aurora/main.tf
> +  alarm_name        = "${var.aurora_db_instance_name}-aurora_cpu_surplus_credits_charged"
Heller `-` enn `_`, så matcher det de andre alarmene :D

2024-05-23 08:49 UTC, nicolaei commented on modules/aurora/main.tf
>  resource "aws_cloudwatch_metric_alarm" "aurora_cpu_surplus_credits_charged" {
Denne burde hete `this`

2024-05-23 09:41 UTC, nicolaei approved these changes
🔥🔥🔥

2024-05-23 09:42 UTC, merged

2024-05-23 09:42 UTC, nicolaei commented
`0.6.0` 👀